version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  movie_vault_app:
    build: .
    container_name: movie_vault_app
    ports:
      - "${PORT}:${PORT}"
    links:
      - "db:${DB_NAME}"

    restart: unless-stopped
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL:-postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - WORKING_DIR=/code
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db

volumes:
  db_data: