version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - PGPORT=5432
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - movie_vault_db_network
  movie_vault_app:
    build: .
    container_name: movie_vault_app
    ports:
      - "${PORT}:8005"
    networks:
      - movie_vault_db_network
    restart: unless-stopped
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL:-postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - WORKING_DIR=/code
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db

volumes:
  db_data:

networks:
  movie_vault_db_network:
    driver: bridge
    name: movie_vault_db_network