# Generated by Django 5.0.2 on 2024-02-29 02:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('surname', models.CharField(db_index=True, max_length=64)),
                ('date_of_birth', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'surname'], name='app_actor_name_c71e2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('surname', models.CharField(db_index=True, max_length=64)),
                ('date_of_birth', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'surname'], name='app_produce_name_c6de81_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('release_date', models.DateField(db_index=True, max_length=64)),
                ('actors', models.ManyToManyField(to='app.actor')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producer')),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'release_date'], name='app_movie_title_055ace_idx')],
            },
        ),
    ]
