# Generated by Django 5.0.2 on 2024-03-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Rename Producer to Director
    """

    dependencies = [
        ('app', '0002_alter_actor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='Movie',  
            old_name='producer',
            new_name='director',
        ),
        migrations.AlterField(
            model_name='Director',
            name='date_of_birth',
            field=models.DateField(db_index=True, null=True, blank=True)
        ),
        migrations.AlterField(
            model_name='Actor',
            name='date_of_birth',
            field=models.DateField(db_index=True, null=True, blank=True)
        ),
    ]
