# Generated by Django 5.0.2 on 2024-03-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240301_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieActorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Movie Actor',
            },
        ),
        migrations.RenameIndex(
            model_name='director',
            new_name='app_directo_name_214a9e_idx',
            old_name='app_produce_name_c6de81_idx',
        ),
        migrations.AddField(
            model_name='movieactorrelation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actor'),
        ),
        migrations.AddField(
            model_name='movieactorrelation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='app.MovieActorRelation', to='app.actor'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'release_date', 'director'], name='app_movie_title_850cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='movieactorrelation',
            index=models.Index(fields=['movie', 'actor'], name='app_movieac_movie_i_5e1e1d_idx'),
        ),
    ]
