# Generated by Django 5.0.2 on 2024-03-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movieactorrelation_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movieactorrelation',
            new_name='app_movie_a_movie_i_e575a8_idx',
            old_name='movie_actor_movie_i_87b358_idx',
        ),
        migrations.AlterModelTable(
            name='movieactorrelation',
            table='app_movie_actor_relation',
        ),
    ]
