"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.2.
"""

from pathlib import Path
import environ
import dj_database_url


env = environ.Env(
    DEBUG=(bool, False)
)

DEBUG = env.bool('DEBUG', False)
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = env.str('SECRET_KEY', '')
TMDB_API_KEY = env.str('TMDB_API_KEY', '')
OMDB_API_KEY = env.str('OMDB_API_KEY', '')

DATABASE_URL = env.str('DATABASE_URL', '')

DB_USER = DB_PASS = DB_NAME = DB_PORT = DB_HOST = None

if not DATABASE_URL:
    DB_USER = env.str('DB_USER')
    DB_PASS = env.str('DB_PASS')
    DB_NAME = env.str('DB_NAME')
    DB_PORT = env.int('DB_PORT')
    DB_HOST = env.str('DB_HOST')
    
    DATABASE_URL = f"postgres://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

db_config = dj_database_url.config(default=DATABASE_URL) 

DB_USER = DB_USER or db_config.get('USER')
DB_PASS = DB_PASS or db_config.get('PASSWORD')
DB_NAME = DB_NAME or db_config.get('NAME')
DB_PORT = DB_PORT or db_config.get('PORT')
DB_HOST = DB_HOST or db_config.get('HOST')


DATABASES = {
    'default': db_config
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'django_filters',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'
STATIC_ROOT = Path.joinpath(BASE_DIR, STATIC_URL)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
